version: '3.9'

networks:
  backend:

services:
  app_test:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_ENV=dev
    ports:
      - 13000:3000
    networks:
      - backend

  app_prod:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_ENV=prod
    ports:
      - 23000:3000
    networks:
      - backend