version: '3.9'

networks:
  backend:

services:
  app_test:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=development
        - NEXT_PUBLIC_CLIENT_ENV="Dev Value"
    ports:
      - 13000:3000
    networks:
      - backend

  app_prod:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_CLIENT_ENV="Prod Value"
    ports:
      - 23000:3000
    networks:
      - backend