apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.grpcNodePort))) }}
      nodePort: {{ .Values.service.grpcNodePort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}
